### ISSUE TITLE
Add command for giving user a chapter role

### ISSUE THREAD

**Issue by lucubrator** [datasektionen/harmony#42]
### Add command for giving the user a chapter role

The command is for those who never received a chapter role. Mainly, this happens when the student never got added to Mottagningen's admissions list. 

**Context:** In preparation for Mottagningen, a list of admitted nØllan students is sent to D-sys (@mathiasmagnusson), who then uses a script to fill in the Hodis year tag for each student (@elmaxe and/or @niklasvatn wrote the script).

- [ ] Add a command that lets the user assign herself to a chapter and receive either the @Datasektionen role or @Extern.
- [ ] The command should only be visible to users without a chapter role (@Datasektionen | @Extern). 

### Priority
This command should not be worked on before everything related to Mottagningen is done.

**Comment by Benjaneb** [comment]
If we wanted this it could nowadays be done easily with Discord's "onboarding" (no need for Harmony). Though I'm not even sure if we want external people to be able to assign themselves the datasektionen role, if there's any issues with seeing the SM val, motioner and propositioner.
